# Driver Drowsiness Detection Configuration

# Camera settings
camera:
  device_id: 0  # Camera device ID (usually 0 for built-in webcam)
  resolution: [640, 480]  # Width, Height
  fps: 30  # Frames per second

# Detection settings
detection:
  face_confidence: 0.5  # Minimum confidence for face detection (0.0 to 1.0)
  eye_aspect_ratio_threshold: 0.3  # Threshold for eye aspect ratio (higher is more sensitive)
  consecutive_frames_threshold: 30  # Number of consecutive frames to confirm drowsiness

# Drowsiness thresholds
drowsiness:
  normal:
    ear_threshold: 0.3  # EAR threshold for normal drowsiness
    duration_threshold: 2  # Duration (seconds) for normal drowsiness alert
    message: "Hey, are you awake? Please respond."
  extreme:
    ear_threshold: 0.2  # EAR threshold for extreme drowsiness
    duration_threshold: 2  # Duration (seconds) for extreme drowsiness alert
    message: "Warning! You appear to be falling asleep! Wake up now!"

# Alert settings
alerts:
  volume: 0.8  # Volume level (0.0 to 1.0)

# Face detection alerts
face_detection:
  alert_interval: 5.0  # Time in seconds between alerts when no face is detected
  message: "No face detected! Please position yourself in front of the camera."

# Add this section to your config.yaml file
gemini:
  api_key: "AIzaSyBV6KJlTxlda-BrpqUwl1Hm-PNNh4r7KKU"  # Replace with your actual API key
  api_url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent"

file_path:
  status_file: "/tmp/drowsiness_status.txt"
  relevant_topics_file: "/tmp/relevant_driver_topics.txt"

models:
  piper_model_path: "models/piper/model_voice.onnx"
  vosk_model_path: "models/vosk-model-small-en-us-0.15"
  distilbert_model_path: "models/distilbert"
  tinyllama_model_path: "models/tinyllama"