# Driver Drowsiness Detection Configuration

# Camera settings
camera:
  device_id: 0  # Camera device ID (usually 0 for built-in webcam)
  resolution: [640, 480]  # Width, Height
  fps: 30  # Frames per second

# Detection settings
detection:
  face_confidence: 0.5  # Minimum confidence for face detection (0.0 to 1.0)
  eye_aspect_ratio_threshold: 0.3  # Threshold for eye aspect ratio (higher is more sensitive)
  consecutive_frames_threshold: 20  # Number of consecutive frames to confirm drowsiness

# Drowsiness thresholds
drowsiness:
  normal:
    ear_threshold: 0.3  # EAR threshold for normal drowsiness
    duration_threshold: 1.5  # Duration (seconds) for normal drowsiness alert
    message: "Hey, are you awake? Please respond."
  extreme:
    ear_threshold: 0.25  # EAR threshold for extreme drowsiness
    duration_threshold: 1.5  # Duration (seconds) for extreme drowsiness alert
    message: "Warning! You appear to be falling asleep! Wake up now!"

# Alert settings
alerts:
  volume: 0.8  # Volume level (0.0 to 1.0)

# Face detection alerts
face_detection:
  alert_interval: 5.0  # Time in seconds between alerts when no face is detected
  message: "No face detected! Please position yourself in front of the camera."

# Add this section to your config.yaml file
gemini:
  api_key: "AIzaSyBV6KJlTxlda-BrpqUwl1Hm-PNNh4r7KKU"  # Replace with your actual API key
  api_url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent"

status_file_path:
  path: "/tmp/drowsiness_status.txt"

audio_alerts:
  messages:
    normal: "Are you feeling sleepy? Please respond."
    extreme: "You seem very drowsy. Respond to confirm you're awake."
    no_face: "No driver detected. Please ensure you're in view."
  volume: 1.0
  piper_model_path: "models/piper/model_voice.onnx"
  vosk_model_path: "models/vosk-model-small-en-us-0.15"
  phi3_model_path: "models/Phi-3-mini-4k-instruct-q4.gguf"